### ISSUE TITLE
Information/Feature Idea

### ISSUE THREAD

**Issue by mmiller7** [furrtek/PrecIR#8]
I understand from the ReadMe that the data-rates are unusually high so I don't know the feasibility of this idea, but thought I would ask.

The [Flipper Zero has an IR emitter](https://docs.flipperzero.one/infrared) and can support custom made applications as well as [GPIO output signals](https://docs.flipperzero.one/gpio-and-modules).  Have you explored if this could be ported to run on that device either with built-in IR emitter or a simple GPIO addon, allowing with a dynamic input of the required serial/ID to select from more than one "picture" to send to a different tag "on-demand"?

**Comment by furrtek** [comment]
The Flipper Zero is entirely capable of sending IR frames to these price tags without any add-on.

Unfortunately, several FZ owners had the great idea to beg / try to pull me into writing such an app, effectively annoying the life out of me. Some months ago, I got dragged into a dedicated Telegram group and spent several hours in it trying to steer people in the right direction, but in the end not a single line of code was written. Since noone was going anywhere and since I wasn't going to give into the begging, someone just decided to delete the group overnight. Total waste of time.

The simple fact that these people are putting more energy into making others work instead of doing the work theirselves, is honestly pitiful. I'm sorry but I will -NOT- work for free for consumer-minded people.

**Comment by mmiller7** [comment]
Fair enough!  Its interesting to hear you got far enough to verify it is capable of sending the signals.  Maybe some day if I find time to learn coding for Flipper apps I'll explore how hard it would be to port over, but for now I can relate with so many other things competing for my time as well.

Closing the ticket as that seems the reasonable thing to do at this point.  Cheers!

**Comment by furrtek** [comment]
Will add the info (minus my uncalled-for criticism) in the readme file.
